### ISSUE TITLE
update import from hydrus.hydraspec to hydra_python_core

### ISSUE THREAD

**Issue by knakul853** [HTTP-APIs/hydra-flock-central-controller#16]
there is need to change all the imports from hydrus.hydraspec to  hydra_python_core  and include ```git+https://github.com/http-apis/hydra-python-core.git@(hash/version)#egg=hydra_python_core ```within the requirements.txt file

**Comment by Mec-iS** [comment]
@Guttz Please take a look if this is still a thing

**Comment by Guttz** [comment]
There are no hydraspec imports left on the demo, @xadahiya fixed this already. This issue can be closed.

However, investigating this I found some left on hydrus and made the fix and opened a PR https://github.com/HTTP-APIs/hydrus/pull/387
